In [3]:
import torch
import numpy as np

In [10]:
inputs = np.array(
    [
        [73, 67, 43],
        [91, 88, 64],
        [87, 134, 58],
        [102, 43, 37],
        [69, 96, 70]
    ],dtype='float32'
)


In [11]:
targets = np.array(
    [
        [56, 70],
        [81, 101],
        [119, 133],
        [22, 37],
        [103, 119]
    ], dtype='float32'
)

In [12]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)


tensor([[-2.3862, -0.6946, -2.3011],
        [ 1.0345,  0.7829,  0.8296]], requires_grad=True)
tensor([1.3175, 1.6002], requires_grad=True)


In [14]:
inputs = inputs.t()
targets = targets.t()

In [15]:
w = torch.randn(3, 2, requires_grad=True)

In [34]:
b = torch.randn(2, 1, requires_grad=True)

In [35]:
print(w)

tensor([[ 0.2550, -1.8782],
        [-0.1655,  1.5910],
        [-0.3972,  0.0539]], requires_grad=True)


In [36]:
print(b)

tensor([[ 1.0831],
        [-0.5138]], requires_grad=True)


In [37]:
b.size()

torch.Size([2, 1])

In [38]:
w.size()

torch.Size([3, 2])

In [39]:
def model(x):
    return w.t() @ x + b

In [40]:
preds = model(inputs)
print(preds)

tensor([[  -8.4718,  -15.6988,  -21.9490,    5.2779,  -25.0154],
        [ -28.7129,  -27.9795,   52.3940, -121.6869,   26.3918]],
       grad_fn=&lt;AddBackward0&gt;)


In [44]:
print(targets)

tensor([[ 56.,  81., 119.,  22., 103.],
        [ 70., 101., 133.,  37., 119.]])


In [45]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [46]:
loss = mse(preds, targets)

In [47]:
mse(preds, targets)

tensor(11667.6543, grad_fn=&lt;DivBackward0&gt;)

In [48]:
preds - targets

tensor([[ -64.4718,  -96.6988, -140.9490,  -16.7221, -128.0154],
        [ -98.7129, -128.9795,  -80.6060, -158.6869,  -92.6082]],
       grad_fn=&lt;SubBackward0&gt;)

In [52]:
loss.backward()

In [64]:
print(w)
print(w.grad)

tensor([[ 0.3276, -1.7811],
        [-0.0761,  1.6799],
        [-0.3438,  0.1129]], requires_grad=True)
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [65]:
w.grad.zero_()
b.grad.zero_()

tensor([[0.],
        [0.]])

In [66]:
preds = model(inputs)
print(preds)

tensor([[   5.1207,    2.2013,   -0.5454,   18.5088,   -7.6767],
        [ -13.1265,   -7.5376,   76.1854, -105.7750,   45.7643]],
       grad_fn=&lt;AddBackward0&gt;)


In [67]:
loss = mse(preds, targets)
loss.backward()
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()


In [68]:
print(w)
print(b)

tensor([[ 0.3861, -1.7001],
        [-0.0018,  1.7517],
        [-0.2997,  0.1614]], requires_grad=True)
tensor([[ 1.0847],
        [-0.5117]], requires_grad=True)


In [79]:
for i in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [80]:
preds = model(inputs)

In [81]:
loss = mse(preds, targets)
print(loss)

tensor(1.5356, grad_fn=&lt;DivBackward0&gt;)


In [82]:
preds


tensor([[ 57.4332,  81.3656, 120.1789,  21.4832, 100.4360],
        [ 70.3082, 100.0310, 134.4120,  37.4290, 117.6865]],
       grad_fn=&lt;AddBackward0&gt;)

In [83]:
targets

tensor([[ 56.,  81., 119.,  22., 103.],
        [ 70., 101., 133.,  37., 119.]])

In [84]:
import torch.nn as nn


In [86]:
from torch.utils.data import TensorDataset

In [90]:
train_ds = TensorDataset(inputs.t(), targets.t())
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [91]:
targets = targets.t()
inputs = inputs.t()

In [92]:
from torch.utils.data import DataLoader

In [93]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [138]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [119., 133.],
        [ 81., 101.],
        [ 56.,  70.]])


In [139]:
model = nn.Linear(3, 2)

In [140]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4327, -0.0088, -0.4900],
        [ 0.1136,  0.0021, -0.2364]], requires_grad=True)
Parameter containing:
tensor([-0.1541, -0.4497], requires_grad=True)


In [143]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4327, -0.0088, -0.4900],
         [ 0.1136,  0.0021, -0.2364]], requires_grad=True),
 Parameter containing:
 tensor([-0.1541, -0.4497], requires_grad=True)]

In [144]:
preds = model(inputs)
preds

tensor([[-53.3997,  -2.1784],
        [-71.6631,  -5.0532],
        [-67.3964,  -3.9912],
        [-62.7962,   2.4840],
        [-65.1547,  -8.9544]], grad_fn=&lt;AddmmBackward&gt;)

In [145]:
import torch.nn.functional as F

In [146]:
loss_fn = F.mse_loss

In [147]:
loss = loss_fn(model(inputs), targets)

In [148]:
print(loss)

tensor(15827.1592, grad_fn=&lt;MseLossBackward&gt;)


In [149]:
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb, yb, in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [151]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [162]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 9.6863
Epoch [20/100], Loss: 9.5163
Epoch [30/100], Loss: 9.3494
Epoch [40/100], Loss: 9.1857
Epoch [50/100], Loss: 9.0250
Epoch [60/100], Loss: 8.8673
Epoch [70/100], Loss: 8.7125
Epoch [80/100], Loss: 8.5606
Epoch [90/100], Loss: 8.4115
Epoch [100/100], Loss: 8.2651


In [163]:
preds = model(inputs)
preds

tensor([[ 57.3649,  70.4883],
        [ 80.3786,  98.6449],
        [122.5295, 137.2750],
        [ 22.1889,  38.2755],
        [ 98.0644, 114.7909]], grad_fn=&lt;AddmmBackward&gt;)

In [164]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])